project:
  type: book
  output-dir: "."
  
book:
  title: "<span style='color: black;'>CASA0025-Group Application</span>" 
  author: "Freeload group"
  favicon: "img/ucl.png"
  navbar:
    logo: "img/casa_logo.jpg"
    date: "2024/4/18"
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "<span style='color:black;'>CASA0025</span>" 
    style: docked
    reader-mode: true
  repo-url: https://github.com/LaneyGUO/CASA0025-GroupWork-FreeLoad.git
  repo-actions: [issue]
  chapters:
    - index.qmd

bibliography: references.bib


format:
  html:
    theme: cosmo
    code-link: true
    fontsize: 14pt
  pdf:
    documentclass: article
    fontsize: 14pt

editor: visual